### PR TITLE
Switch to v2 of the aws sdk

### PR DESCRIPTION
**Pull request by guenhter**
Amazon has a version 2 of the api which is already the official predecessor of v1.

The main advantages of the new API are performance improvements, easier error handling, easier credentials handling, ...

https://aws.amazon.com/blogs/developer/client-updates-in-the-preview-version-of-the-aws-sdk-for-go-v2/

### CODE REVIEW

**Comment by guenhter** [comment]
This is of course a breaking change.

**Comment by guenhter** [comment]
Fair enough.
I'll keep this MR open if you don't mind ... just in case.

**Comment by thomasf** [comment]
This can either just be published as a new major version (not breaking any current users) or be published as a separate package, maybe by @guenhter just like aws-go-sdk-v2 is.

**Comment by jszwec** [comment]
Yes it could be published as a v2, but then v1 is far from being deprecated due to the fact how popular aws sdk v1 is.
This also means that there will be two versions of the library to maintain. Considering the current popularity of aws sdk v1, is it really worth it?

**Comment by guenhter** [comment]
@jszwec The v2 of the api has some big benefits. It has a nicer configuration handling (not in regard to the go api but v2 allows e.g. to define the region in ~/.aws/config). 
So having v2 is usually a good way. I still see your point that v1 is still  heavily used. 
Do you want me just to start off a own library (like @thomasf  suggested) named s3fs-v2?

**Comment by thomasf** [comment]
@guenhter Since this is a breaking change I would suggest adding a context argument  to s3fs.New while you are at it so we get better canceling.

**Comment by guenhter** [comment]
@thomasf Good idea. Done. Could you have another look if you like it that way.

**Comment by thomasf** [comment]
> @thomasf @guenhter What is the point of providing context to New? FS is supposed to be a long lived var, so it's not like you are going to be recreating FS for every request to have cancellations, and fs.FS doesn't support context per Read. Could you please elaborate?

It doesn't have to be a long lived variable, a struct like this is cheap and can be instantiated every time a request is handled if you want all AWS client communication to cancel if an HTTP request is closed by a client in a request handler (or whatever).
You are correct that it is a kind of a blunt tool because it doesn't work on a per file system request basis but it is still useful.

**Comment by thomasf** [comment]
I think you might to check the context for errors before new calls. Not sure if this is the best way to do it.

```
diff --git a/fs.go b/fs.go
index fe74df5..7ca2179 100644
--- a/fs.go
+++ b/fs.go
@@ -119,6 +119,13 @@ func (f *S3FS) Open(name string) (fs.File, error) {

 // Stat implements fs.StatFS.
 func (f *S3FS) Stat(name string) (fs.FileInfo, error) {
+       if err := f.context.Err(); err != nil {
+               return nil, &fs.PathError{
+                       Op:   "stat",
+                       Path: name,
+                       Err:  err,
+               }
+       }
        fi, err := stat(f.context, f.s3Api, f.bucket, name)
        if err != nil {
                return nil, &fs.PathError{
diff --git a/fs_integration_test.go b/fs_integration_test.go
index b0d0f49..ce43d6e 100644
--- a/fs_integration_test.go
+++ b/fs_integration_test.go
@@ -567,6 +567,32 @@ func TestFS(t *testing.T) {
                        testFn(t, f.s3fs)
                })
        }
+
+       t.Run("test cancel context", func(t *testing.T) {
+               ctx, cancel := context.WithCancel(context.Background())
+               fsys := s3fs.New(ctx, s3cl, *bucket)
+               {
+                       fi, err := fsys.Stat(".")
+                       if err != nil {
+                               t.Fatal(err)
+                       }
+                       if fi == nil {
+                               t.Fatal("file info is nil")
+                       }
+               }
+               cancel()
+               {
+                       fi, err := fsys.Stat(".")
+                       if err == nil {
+                               t.Fatal("expected error")
+                       }
+                       if fi != nil {
+                               t.Fatal(fi)
+                       }
+               }
+
+       })
+
 }

 func newClient(t *testing.T) s3fs.S3Api {
```

**Comment by jszwec** [comment]
fair enough

context errors dont need to be checked like you propose. S3 client should be responsible for doing that.

**Comment by thomasf** [comment]
yeah I am not sure why the test doesn't fail unless I add it explicitly, maybe there is a problem somewhere else.

**Comment by thomasf** [comment]
oh, I see. I accidentally tested the stat for "." which is a hard coded return of a dir entry in fs.go and does not make any aws api calls. So no issue at all.

**Pull request closed without merging**
